In [6]:
# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [7]:
# Import libraries
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.drop(["User ID","Purchased"],axis=1).values
y = dataset.Purchased.values.reshape(-1,1)

In [8]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
X[:,0] = encode.fit_transform(X[:,0])

In [9]:
# Training Set and Testing Set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# Decision Tree

In [10]:
# Build a decision tree model
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=0)
model.fit(X_train,y_train.ravel())

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [11]:
# Test model
y_pred = model.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[53,  5],
       [ 3, 19]], dtype=int64)

# Random Forest Tree

In [43]:
# Build Random forest model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier().fit(X_train,y_train.ravel())

In [44]:
# Test model
y_pred = model.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[54,  4],
       [ 3, 19]], dtype=int64)

In [45]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[10,15,20,25,30,35],'random_state':[3,7,10,13,17]}]

In [46]:
grid_search = GridSearchCV(estimator=model,param_grid=parameters,scoring="accuracy",cv=10)
grid_search = grid_search.fit(X_train,y_train.ravel())
best_parameters = grid_search.best_params_
best_parameters

{'n_estimators': 15, 'random_state': 3}

In [47]:
# Improved Random forest model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=15,random_state=3).fit(X_train,y_train.ravel())

In [48]:
# Test model
y_pred = model.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[55,  3],
       [ 2, 20]], dtype=int64)