In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
dataset = pd.read_csv("house-votes-84.csv",names=["party","infants","water","budget","physician","salvador","religious","satellite","aid","missile","immigration","synfuels","education","superfund","crime","duty_free_exports","eaa_rsa"])

In [3]:
dataset = dataset.replace(['y','n','?'],[0,1,"nan"])

In [6]:
X = dataset.drop("party",axis=1).values
y = dataset.party.values

In [7]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
y[:,0] = encode.fit_transform(y[:,0])

IndexError: too many indices for array

In [9]:
y = y.reshape(435,1)

In [10]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
y[:,0] = encode.fit_transform(y[:,0])

In [11]:
y

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
    

In [12]:
from sklearn.preprocessing import Imputer
imputerNaN = Imputer(missing_values="NaN",strategy="most_frequent",axis=0)
X = imputerNaN.fit_transform(X[:,:])

In [18]:
y=y.astype('int')

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
y_pred = model.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[51  1]
 [ 2 33]]


In [24]:
84/87

0.9655172413793104

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [33]:
y_pred = knn.predict(X_test)

In [34]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[48,  4],
       [ 3, 32]], dtype=int64)